# Generated by Django 3.0.4 on 2020-03-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_prod_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pcategory',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='pimage',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='psubcategory',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='pdesc',
            field=models.CharField(max_length=300),
        ),
    ]
