# Generated by Django 3.0.4 on 2020-03-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_ordertrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tprice',
            field=models.IntegerField(default=0),
        ),
    ]
